name: EMCAddons
version: '1.0'
main: org.breakthebot.EMCAddons.EMCAddons
api-version: '1.21'
authors: [ Veyronity ]
folia-supported: true
commands:
  eventmanager:
    aliases: ["em", "event", "game"]
    description: Manage all server hosted events
  hide:
    aliases: ["hidenseek"]
    description: Manage Hide & Seek Event
  tag:
    description: Manage Tag Event

permissions:
  ly.skynet.specvanish:
    default: op
    description: Grant permission to hide from all non-immune online players while in spectator mode

  ly.skynet.see.specvanish:
    default: op
    description: Grant permission to see all players regardless of their vanish status


  eventmanager.admin:
    default: op
    description: Grant all eventmanager permissions
    children:
      eventmanager.broadcast: true
      eventmanager.list: true
      eventmanager.hide-n-seek: true
      eventmanager.tag: true

  eventmanager.hide-n-seek:
    default: op
    description: Grant all Hide & Seek Event Management permissions
    children:
      eventmanager.hide-n-seek.event.create: true
      eventmanager.hide-n-seek.event.start: true
      eventmanager.hide-n-seek.event.end: true
      eventmanager.hide-n-seek.manage.players: true
      eventmanager.hide-n-seek.manage.hunters: true
      eventmanager.hide-n-seek.giveall: true
      eventmanager.hide-n-seek.status: true

  eventmanager.tag:
    default: op
    description: Grant all Tag Event Management permissions
    children:
      eventmanager.tag.event.create: true
      eventmanager.tag.event.start: true
      eventmanager.tag.event.end: true
      eventmanager.tag.manage.players: true
      eventmanager.tag.status: true